version: '3.12.0'

services:
  web:
    build: .
    command: 
      python /backend/manage.py runserver 0.0.0.0:8000

    volumes:
      - ./backend:/backend

    ports:
      - "8001:8000"
      
    environment:
      DEBUG: "1"
