# Generated by Django 5.0.1 on 2024-02-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='characteristics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
