# Generated by Django 5.0.1 on 2024-02-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_characteristics_product_characteristics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='category',
            name='characteristics_template',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
